default: &default
    adapter: postgresql
    encoding: unicode
    pool: 25
    timeout: 5000

development:
    <<: *default
    database: stringNcup_development
    username: ENV["POSTGRES_USER"]
    password: ENV["POSTGRES_PASS"]

test:
    <<: *default
    database: stringNcup_test
    username: ENV["POSTGRES_USER"]
    password: ENV["POSTGRES_PASS"]

production:
    <<: *default
    database: stringNcup_production
    username: ENV["POSTGRES_USER"]
    password: ENV["POSTGRES_PASS"]